# # https://drift.simonbinder.eu/docs/advanced-features/builder_options/
targets:
  $default:
    # disable the default generators, we'll only use the non-shared drift generator here
    auto_apply_builders: false
    builders:
      drift_dev|not_shared:
        enabled: true
      drift_dev|preparing_builder:
        enabled: true

  run_built_value:
    dependencies: ['clippy']
    builders:
      # Disable drift_dev builders. By default, those would run on each target
      drift_dev:
        enabled: false
      drift_dev|preparing_builder:
        enabled: false
      # we don't need to disable moor_generator_not_shared, because it's disabled by default

